### ISSUE TITLE
cant connect to hybrid instances

### ISSUE THREAD

**Issue by kranthisai** [somoore/ShellofACloud#3]
Hi, 
 ShellofACloud is working only for EC2 instances. It is not working for on premise instances. I registered my ubuntu machine in AWS SSM. Looks like SSM manager API socket messages were different for on prem instances. I see some msg types like pause_publication, start_publication. i dont see any acknowledge messageTypes

**Comment by somoore** [comment]
sorry for the delay on the response. Thanks for the heads up - I have not yet tried this with on-premises instances, but I will look into this and get a fix going. Thanks!

**Comment by Nabeelperson** [comment]
Hi,

My team and I have solved what to do with regards to pause_publication and start_publication. For pause_publication message you just need to acknowledge it in the same way to output_stream_data message and for start_publication you need to acknowledge it, and also resend the handshake message and reset you outgoing sequence number to 0.

**Comment by somoore** [comment]
> Hi,
> 
> My team and I have solved what to do with regards to pause_publication and start_publication. For pause_publication message you just need to acknowledge it in the same way to output_stream_data message and for start_publication you need to acknowledge it, and also resend the handshake message and reset you outgoing sequence number to 0.

Thank you for the heads up! I will make that change as well.
